[package]
name = "gtrust"
version = "0.1.0"
authors = ["gttmy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "step0_repl"
path = "src/step0_repl.rs"
